### ISSUE TITLE
Layer and Recipe only for CANBOAT

### ISSUE THREAD

**Issue by shantanoo-desai** [overtane/meta-signalk#1]
Hi,

Maybe creating a `meta` layer only for the [CANBOAT](https://github.com/canboat/canboat) would be interesting.

I am looking into it and found out that Yocto does support `Makefile` [Link](https://www.yoctoproject.org/docs/1.4.2/dev-manual/dev-manual.html#usingpoky-extend-addpkg-makefile)

I was wondering if you are following the documentation of Yocto or using some tutorials for the creating this meta layer.

This might be helpful for the community who just want canboat as a stand-alone NMEA2K parser in Yocto

**Comment by overtane** [comment]
Hi! Yocto is useful if you want to assemble your own distro and build everything from scratch. I'm not familiar with CANBOAT, but if it builds from makefiles, it surely can be layered to Yocto. I've found Yocto documentation sometimes too heavy and plentiful. Instead, there are some good text books around like https://www.packtpub.com/virtualization-and-cloud/embedded-linux-development-using-yocto-projects-second-edition, which you may want to grab, if you plan to start digging into subject. Yocto has some tools like recipetool and devtool, which help you to generate the build recipes. I recommend looking into those also.  

Is CANBOAT something that can be used in combination with SignalK server?

**Comment by shantanoo-desai** [comment]
The Repository is for the NMEA2000. I think that the people have written a Javascript library called __canboatjs__. But I am pretty sure that the it is used in SignalK for storing information from the on-board systems.

**Comment by shantanoo-desai** [comment]
Just so you know [meta-canboat](https://github.com/shantanoo-desai/meta-canboat) is now the repository to use binaries for Canboat.

Closing the issue and thanks.
